from app import db, app
from app.models import User, Post

app_context = app.app_context()
app_context.push()
db.drop_all()
db.create_all()

u1 = User(username='wai', email='wai@example.com')
u2 = User(username='tony', email='tony@example.com')
u3 = User(username='tim', email='tim@example.com')
u4 = User(username='sam', email='sam@example.com')
u1.set_password("w")
u2.set_password("t")
u3.set_password("t")
u4.set_password("s")
db.session.add_all([u1, u2, u3, u4])

# Mock lessons data as posts
p1 = Post(title='平假名、片假名的學習和練習', body='平假名、片假名的學習和練習')
p2 = Post(title='發音練習：母音、清音、濁音、拗音、促音、長音', body='發音練習：母音、清音、濁音、拗音、促音、長音')
p3 = Post(title='基本句型結構 (SOV)', body='基本句型結構 (SOV)')
p4 = Post(title='基本詞彙 (挨拶、物品名稱、數字等)', body='基本詞彙 (挨拶、物品名稱、數字等)')
p5 = Post(title='助詞的使用 (が、を、は、に、へ、で、の)', body='助詞的使用 (が、を、は、に、へ、で、の)')
p6 = Post(title='基本問候語', body='基本問候語')
p7 = Post(title='自我介紹', body='自我介紹')
p8 = Post(title='日常對話練習 (購物、餐飲、問路)', body='日常對話練習 (購物、餐飲、問路)')
p9 = Post(title='五段動詞、一段動詞、不規則動詞', body='五段動詞、一段動詞、不規則動詞')
p10 = Post(title='動詞變化 (ます形、て形、ない形等)', body='動詞變化 (ます形、て形、ない形等)')
p11 = Post(title='時態 (過去形、否定形等)', body='時態 (過去形、否定形等)')
p12 = Post(title='基礎漢字的介紹與練習', body='基礎漢字的介紹與練習')
p13 = Post(title='常用漢字的寫法與讀法', body='常用漢字的寫法與讀法')
p14 = Post(title='漢字的組詞與運用', body='漢字的組詞與運用')
p15 = Post(title='簡單的短文和對話', body='簡單的短文和對話')
p16 = Post(title='理解與翻譯練習', body='理解與翻譯練習')
p17 = Post(title='簡單對話與段落的聆聽', body='簡單對話與段落的聆聽')
p18 = Post(title='答題與摘要', body='答題與摘要')
p19 = Post(title='自我表達練習', body='自我表達練習')
p20 = Post(title='模擬場景對話練習', body='模擬場景對話練習')
p21 = Post(title='節日與習俗', body='節日與習俗')
p22 = Post(title='飲食文化', body='飲食文化')
p23 = Post(title='日常生活與社交禮儀', body='日常生活與社交禮儀')

db.session.add_all([p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14, p15, p16, p17, p18, p19, p20, p21, p22, p23])
db.session.commit()