from app import db, app
from app.models import User, Post

app_context = app.app_context()
app_context.push()
db.drop_all()
db.create_all()

# Mock Admin account
admin = User(username='admin', email='admin@example.com', is_admin=True)
admin.set_password("112233")
db.session.add(admin)

# Mock users Account
u1 = User(username='u1', email='u1@example.com')
u2 = User(username='u2', email='u2@example.com')
u3 = User(username='u3', email='u3@example.com')
u4 = User(username='alice', email='alice@example.com')
u5 = User(username='bob', email='bob@example.com')
u6 = User(username='charlie', email='charlie@example.com')
u7 = User(username='david', email='david@example.com')
u8 = User(username='eve', email='eve@example.com')
u9 = User(username='frank', email='frank@example.com')
u10 = User(username='grace', email='grace@example.com')
u1.set_password("1")
u2.set_password("2")
u3.set_password("3")
u4.set_password("4")
u5.set_password("5")
u6.set_password("6")
u7.set_password("7")
u8.set_password("8")
u9.set_password("9")
u10.set_password("10")
db.session.add_all([u1, u2, u3, u4, u5, u6, u7, u8, u9, u10])

# Mock posts
p1 = Post(title='My first post', body='This is the body of my first post', user_id=u1.id)
p2 = Post(title='A day in the life', body='Today I went to the park and had a great time.', user_id=u2.id)
p3 = Post(title='Learning Python', body='Python is a versatile programming language.', user_id=u3.id)
p4 = Post(title='Traveling to Japan', body='Japan is a beautiful country with rich culture.', user_id=u4.id)
p5 = Post(title='My favorite recipes', body='I love cooking and trying out new recipes.', user_id=u5.id)
p6 = Post(title='Fitness journey', body='Staying fit and healthy is important.', user_id=u6.id)
p7 = Post(title='Book recommendations', body='Here are some books I recommend reading.', user_id=u7.id)
p8 = Post(title='Photography tips', body='Photography is a great hobby to capture moments.', user_id=u8.id)
p9 = Post(title='Gardening 101', body='Gardening is a relaxing and rewarding activity.', user_id=u9.id)
p10 = Post(title='Tech trends', body='Keeping up with the latest in technology.', user_id=u10.id)
p11 = Post(title='Music I love', body='Sharing my favorite music tracks.', user_id=u1.id)
p12 = Post(title='Movie reviews', body='My thoughts on the latest movies.', user_id=u2.id)
p13 = Post(title='DIY projects', body='Do-it-yourself projects are fun and creative.', user_id=u3.id)
p14 = Post(title='Mindfulness and meditation', body='Practicing mindfulness for a better life.', user_id=u4.id)
p15 = Post(title='Career advice', body='Tips and advice for advancing your career.', user_id=u5.id)
p16 = Post(title='Learning new languages', body='The benefits of learning new languages.', user_id=u6.id)
p17 = Post(title='Home decor ideas', body='Ideas to decorate your home beautifully.', user_id=u7.id)
p18 = Post(title='Pet care tips', body='Taking care of your pets.', user_id=u8.id)
p19 = Post(title='Outdoor adventures', body='Exploring the great outdoors.', user_id=u9.id)
p20 = Post(title='Healthy eating', body='Tips for maintaining a healthy diet.', user_id=u10.id)
p21 = Post(title='Personal finance', body='Managing your personal finances effectively.', user_id=u1.id)
p22 = Post(title='Hiking trails', body='Best hiking trails to explore.', user_id=u2.id)
p23 = Post(title='Yoga for beginners', body='Starting your yoga journey.', user_id=u3.id)

db.session.add_all([p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14, p15, p16, p17, p18, p19, p20, p21, p22, p23])
db.session.commit()