"""added ChatSettings

Revision ID: 107a12c841e1
Revises: 
Create Date: 2025-01-04 15:49:17.235496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '107a12c841e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('debug', sa.Boolean(), nullable=True),
    sa.Column('headless', sa.Boolean(), nullable=True),
    sa.Column('word_limit', sa.Integer(), nullable=True),
    sa.Column('condition', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_settings_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_settings_timestamp'))

    op.drop_table('chat_settings')
    # ### end Alembic commands ###
