"""Remove user_id from ChatSettings

Revision ID: 6ee3a2e393cd
Revises: 107a12c841e1
Create Date: 2025-01-04 16:21:38.431611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ee3a2e393cd'
down_revision = '107a12c841e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_settings', schema=None) as batch_op:
        batch_op.drop_constraint('chat_settings_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('chat_settings_user_id_fkey', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
